const vids = [{"l":"https://www.dropbox.com/s/86er7xpywi0r0ra/lndrmt.mp4?raw=1","p":"blo1"},
              {"l":"https://www.dropbox.com/s/zqel8vtuvr80c9p/hrm7.mp4?raw=1","p":"gen"},
              {"l":"https://www.dropbox.com/s/u5vgs6zh8nzmfad/jsmnwbbfktx1.mp4?raw=1","p":"black"},
              {"l":"https://www.dropbox.com/s/m532xyyzxpv4ymx/krlmntngnclgst.mp4?raw=1","p":"red2"},
              {"l":"https://www.dropbox.com/s/nz8nwzicvb5amfv/krlmntnmssr.mp4?raw=1","p":"red2"},
              {"l":"https://www.dropbox.com/s/wb5qzw59ccplnyu/mlbntlwq.mp4?raw=1","p":"blonet"},
              {"l":"https://www.dropbox.com/s/gin2czywheop62b/grmsctlnd.mp4?raw=1","p":"blon2"},
              {"l":"https://www.dropbox.com/s/ltiada93y1p1f6u/fkdrvscl1.mp4?raw=1","p":"red1"},
              {"l":"https://www.dropbox.com/s/rtcivfsbha6bqdj/fkdrvnscl2.mp4?raw=1","p":"red1"},
              {"l":"https://www.dropbox.com/s/17o8u6ph1qeskze/fkdrvnscl3.mp4?raw=1","p":"red1"},
              {"l":"https://www.dropbox.com/s/3jdho7vnsizkokf/fkdrvnscl4.mp4?raw=1","p":"red1"},
              {"l":"https://www.dropbox.com/s/uoyd2ft01ghg6oe/fkdrvnscl5.mp4?raw=1","p":"red1"},
              {"l":"https://www.dropbox.com/s/6ya0spiegjudg6x/f89e110dbfdf3.mp4?raw=1","p":"itfmc"},
              {"l":"https://www.dropbox.com/s/29p12bhuhiz8xih/4815.mp4?raw=1","p":"haya"},
              {"l":"https://www.dropbox.com/s/nxp4w7wnh6btjal/brtsclbt.mp4?raw=1","p":"beur"},
              {"l":"https://www.dropbox.com/s/nnb95yz57c4lu4y/hstrltrsty.mp4?raw=1","p":"bw"},
              {"l":"https://www.dropbox.com/s/b8awxc0x4khkrmk/snlsbtrsm.mp4?raw=1","p":"asia"}
             ];
